import { Tender } from './types';

export const mockTenders: Tender[] = [
  {
    id: '1',
    title: 'Строительство жилого комплекса «Солнечный»',
    organization: 'ООО «ГрадСтройИнвест»',
    category: 'construction',
    status: 'active',
    budget: 245000000,
    currency: 'RUB',
    region: 'Москва',
    publishDate: '2026-01-15',
    deadline: '2026-03-01',
    description: 'Строительство жилого комплекса на 450 квартир с подземной парковкой и детской площадкой. Включает все этапы от проектирования до сдачи объекта.',
    requirements: ['Лицензия СРО на строительство', 'Опыт реализации проектов от 100 млн руб.', 'Наличие собственной техники', 'Штат не менее 50 человек'],
    contactPerson: 'Иванов Сергей Петрович',
    contactEmail: 'tender@gradstroy.ru',
    contactPhone: '+7 (495) 123-45-67',
    isFavorite: true,
    isNew: false,
    viewsCount: 342,
    participantsCount: 12,
  },
  {
    id: '2',
    title: 'Разработка информационной системы учёта',
    organization: 'ПАО «ТехноСервис»',
    category: 'it',
    status: 'active',
    budget: 18500000,
    currency: 'RUB',
    region: 'Санкт-Петербург',
    publishDate: '2026-01-20',
    deadline: '2026-02-28',
    description: 'Разработка и внедрение веб-платформы для автоматизации учёта материальных ценностей. Включает модули: складской учёт, документооборот, аналитика.',
    requirements: ['Опыт разработки на React/Node.js', 'Наличие команды от 5 разработчиков', 'Портфолио аналогичных проектов', 'Сертификация ISO 27001'],
    contactPerson: 'Петрова Анна Владимировна',
    contactEmail: 'procurement@technoservice.ru',
    contactPhone: '+7 (812) 987-65-43',
    isFavorite: false,
    isNew: true,
    viewsCount: 156,
    participantsCount: 8,
  },
  {
    id: '3',
    title: 'Поставка медицинского оборудования для клиники',
    organization: 'ГБУЗ «Городская клиническая больница №7»',
    category: 'medical',
    status: 'evaluation',
    budget: 67000000,
    currency: 'RUB',
    region: 'Новосибирск',
    publishDate: '2026-01-10',
    deadline: '2026-02-15',
    description: 'Поставка и установка медицинского оборудования: МРТ-аппарат, УЗИ-система, рентген-аппарат, лабораторное оборудование.',
    requirements: ['Лицензия на медицинскую деятельность', 'Регистрация Росздравнадзора', 'Гарантийное обслуживание от 3 лет', 'Наличие сервисного центра'],
    contactPerson: 'Козлова Мария Ивановна',
    contactEmail: 'zakupki@gkb7.ru',
    contactPhone: '+7 (383) 555-12-34',
    isFavorite: true,
    isNew: false,
    viewsCount: 523,
    participantsCount: 15,
  },
  {
    id: '4',
    title: 'Ремонт и модернизация автодороги М-5',
    organization: 'ФКУ «Упрдор «Прикамье»',
    category: 'transport',
    status: 'active',
    budget: 890000000,
    currency: 'RUB',
    region: 'Пермский край',
    publishDate: '2026-01-18',
    deadline: '2026-04-01',
    description: 'Капитальный ремонт и модернизация участка автодороги М-5 «Урал» протяжённостью 25 км. Включает замену дорожного полотна, укрепление обочин, установку новых ограждений.',
    requirements: ['Допуск СРО на дорожное строительство', 'Опыт работ на федеральных трассах', 'Асфальтобетонный завод в регионе', 'Штат от 200 человек'],
    contactPerson: 'Сидоров Алексей Николаевич',
    contactEmail: 'tender@uprdor.ru',
    contactPhone: '+7 (342) 234-56-78',
    isFavorite: false,
    isNew: true,
    viewsCount: 891,
    participantsCount: 23,
  },
  {
    id: '5',
    title: 'Оснащение школ интерактивным оборудованием',
    organization: 'Департамент образования г. Казань',
    category: 'education',
    status: 'upcoming',
    budget: 32000000,
    currency: 'RUB',
    region: 'Казань',
    publishDate: '2026-02-01',
    deadline: '2026-03-15',
    description: 'Поставка интерактивных панелей, проекторов, компьютерного оборудования для 45 школ города. Включает монтаж и настройку.',
    requirements: ['Авторизация у производителей оборудования', 'Сервисные центры в регионе', 'Опыт поставок в образовательные учреждения', 'Гарантия от 5 лет'],
    contactPerson: 'Хасанова Лилия Ринатовна',
    contactEmail: 'edu-tender@kzn.gov.ru',
    contactPhone: '+7 (843) 345-67-89',
    isFavorite: false,
    isNew: true,
    viewsCount: 78,
    participantsCount: 3,
  },
  {
    id: '6',
    title: 'Строительство солнечной электростанции',
    organization: 'АО «ЭнергоПроект»',
    category: 'energy',
    status: 'active',
    budget: 1200000000,
    currency: 'RUB',
    region: 'Краснодарский край',
    publishDate: '2026-01-12',
    deadline: '2026-03-20',
    description: 'Проектирование и строительство солнечной электростанции мощностью 50 МВт. Включает поставку оборудования, строительно-монтажные работы и пусконаладку.',
    requirements: ['Лицензия на проектирование энергообъектов', 'Опыт строительства СЭС от 10 МВт', 'Наличие инженерного персонала', 'Финансовая гарантия'],
    contactPerson: 'Волков Дмитрий Андреевич',
    contactEmail: 'tender@energo-project.ru',
    contactPhone: '+7 (861) 456-78-90',
    isFavorite: true,
    isNew: false,
    viewsCount: 1204,
    participantsCount: 7,
  },
  {
    id: '7',
    title: 'Организация питания в школах города',
    organization: 'Администрация г. Екатеринбург',
    category: 'food',
    status: 'closed',
    budget: 95000000,
    currency: 'RUB',
    region: 'Екатеринбург',
    publishDate: '2025-12-01',
    deadline: '2026-01-15',
    description: 'Организация горячего питания для учащихся 120 школ города на период 2026 года. Включает разработку меню, поставку продуктов и обслуживание.',
    requirements: ['Опыт организации питания от 50 тыс. порций/день', 'Собственная кухня или комбинат питания', 'Сертификаты HACCP', 'Автопарк для доставки'],
    contactPerson: 'Новикова Елена Сергеевна',
    contactEmail: 'food@ekburg.gov.ru',
    contactPhone: '+7 (343) 567-89-01',
    isFavorite: false,
    isNew: false,
    viewsCount: 445,
    participantsCount: 18,
  },
  {
    id: '8',
    title: 'Консалтинговые услуги по цифровой трансформации',
    organization: 'ПАО «Сбербанк»',
    category: 'consulting',
    status: 'active',
    budget: 45000000,
    currency: 'RUB',
    region: 'Москва',
    publishDate: '2026-01-22',
    deadline: '2026-02-20',
    description: 'Проведение аудита IT-инфраструктуры, разработка стратегии цифровой трансформации, сопровождение внедрения новых технологий.',
    requirements: ['Опыт консалтинга в банковской сфере', 'Команда от 10 сертифицированных специалистов', 'Портфолио проектов цифровой трансформации', 'NDA и безопасность данных'],
    contactPerson: 'Морозов Игорь Валерьевич',
    contactEmail: 'consulting-tender@sberbank.ru',
    contactPhone: '+7 (495) 789-01-23',
    isFavorite: false,
    isNew: true,
    viewsCount: 267,
    participantsCount: 5,
  },
  {
    id: '9',
    title: 'Поставка серверного оборудования для ЦОД',
    organization: 'ФГУП «Ростелеком»',
    category: 'it',
    status: 'evaluation',
    budget: 156000000,
    currency: 'RUB',
    region: 'Москва',
    publishDate: '2026-01-08',
    deadline: '2026-02-10',
    description: 'Поставка серверного оборудования для нового центра обработки данных: 200 стоечных серверов, системы хранения данных, сетевое оборудование.',
    requirements: ['Авторизация у производителей (HPE, Dell, Huawei)', 'Склад в Москве', 'Гарантия от 5 лет с SLA', 'Монтаж и пусконаладка'],
    contactPerson: 'Белов Андрей Константинович',
    contactEmail: 'procurement@rostelecom.ru',
    contactPhone: '+7 (495) 012-34-56',
    isFavorite: true,
    isNew: false,
    viewsCount: 678,
    participantsCount: 11,
  },
  {
    id: '10',
    title: 'Строительство детского сада на 280 мест',
    organization: 'Мэрия г. Воронеж',
    category: 'construction',
    status: 'upcoming',
    budget: 180000000,
    currency: 'RUB',
    region: 'Воронеж',
    publishDate: '2026-02-10',
    deadline: '2026-04-15',
    description: 'Строительство дошкольного образовательного учреждения на 280 мест с бассейном, спортивным и музыкальным залами.',
    requirements: ['Лицензия СРО', 'Опыт строительства социальных объектов', 'Наличие техники', 'Финансовая гарантия не менее 30% от контракта'],
    contactPerson: 'Кузнецова Ольга Дмитриевна',
    contactEmail: 'stroy@voronezh-city.ru',
    contactPhone: '+7 (473) 678-90-12',
    isFavorite: false,
    isNew: true,
    viewsCount: 45,
    participantsCount: 2,
  },
  {
    id: '11',
    title: 'Поставка лекарственных препаратов',
    organization: 'Минздрав Республики Татарстан',
    category: 'medical',
    status: 'active',
    budget: 42000000,
    currency: 'RUB',
    region: 'Казань',
    publishDate: '2026-01-19',
    deadline: '2026-02-25',
    description: 'Поставка лекарственных препаратов для нужд медицинских учреждений республики: антибиотики, обезболивающие, кардиологические препараты.',
    requirements: ['Лицензия на фармацевтическую деятельность', 'Склад с соблюдением температурного режима', 'Регистрация в реестре поставщиков', 'Доставка в течение 48 часов'],
    contactPerson: 'Галиуллин Рустам Фаридович',
    contactEmail: 'pharma@mintzdrav.rt.ru',
    contactPhone: '+7 (843) 789-01-23',
    isFavorite: false,
    isNew: false,
    viewsCount: 312,
    participantsCount: 14,
  },
  {
    id: '12',
    title: 'Разработка мобильного приложения для города',
    organization: 'Правительство Москвы',
    category: 'it',
    status: 'active',
    budget: 28000000,
    currency: 'RUB',
    region: 'Москва',
    publishDate: '2026-01-25',
    deadline: '2026-03-10',
    description: 'Разработка мобильного приложения «Городские сервисы» для iOS и Android. Функционал: оплата ЖКХ, запись к врачу, транспорт, обращения граждан.',
    requirements: ['Опыт мобильной разработки от 3 лет', 'Команда от 8 человек', 'Портфолио приложений с MAU от 100 тыс.', 'Соответствие требованиям ФСТЭК'],
    contactPerson: 'Лебедева Наталья Игоревна',
    contactEmail: 'mobile-app@mos.ru',
    contactPhone: '+7 (495) 234-56-78',
    isFavorite: true,
    isNew: true,
    viewsCount: 198,
    participantsCount: 6,
  },
];

export const categories = [
  { value: 'construction', label: 'Строительство', icon: '🏗️', color: 'bg-orange-100 text-orange-800' },
  { value: 'it', label: 'IT и технологии', icon: '💻', color: 'bg-blue-100 text-blue-800' },
  { value: 'medical', label: 'Медицина', icon: '🏥', color: 'bg-red-100 text-red-800' },
  { value: 'transport', label: 'Транспорт', icon: '🚗', color: 'bg-green-100 text-green-800' },
  { value: 'education', label: 'Образование', icon: '📚', color: 'bg-purple-100 text-purple-800' },
  { value: 'energy', label: 'Энергетика', icon: '⚡', color: 'bg-yellow-100 text-yellow-800' },
  { value: 'food', label: 'Питание', icon: '🍽️', color: 'bg-pink-100 text-pink-800' },
  { value: 'consulting', label: 'Консалтинг', icon: '📊', color: 'bg-indigo-100 text-indigo-800' },
];

export const regions = [
  'Москва', 'Санкт-Петербург', 'Новосибирск', 'Пермский край',
  'Казань', 'Краснодарский край', 'Екатеринбург', 'Воронеж',
];

export const statusLabels: Record<string, { label: string; color: string }> = {
  active: { label: 'Приём заявок', color: 'bg-green-100 text-green-800 border-green-200' },
  upcoming: { label: 'Скоро открытие', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  closed: { label: 'Закрыт', color: 'bg-gray-100 text-gray-800 border-gray-200' },
  evaluation: { label: 'Оценка заявок', color: 'bg-amber-100 text-amber-800 border-amber-200' },
};
